name: Axon Command Authorization

on:
  push:
    branches:
      - main
      - master
      - '*'

jobs:
  build:
    name: Test and Build on JDK ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java-version: 17
            sonar-enabled: false
            deploy-enabled: false
          - java-version: 21
            sonar-enabled: false
            deploy-enabled: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
          cache: "maven"
          server-id: sonatype
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Regular Build
        if: ${{ !matrix.sonar-enabled }}
        run: |
          ./mvnw -B -U -Dstyle.color=always clean verify

      - name: Deploy to Sonatype
        if: success() && matrix.deploy-enabled
        run: |
          ./mvnw -B -U -Dstyle.color=always deploy -DskipTests=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_TOKEN_ID }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_TOKEN_PASS }}
